payment-service.base-url=http://payment-service:8081

spring.r2dbc.url=r2dbc:postgresql://postgres:5432/my-market-app
spring.r2dbc.username=admin
spring.r2dbc.password=admin

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.data.redis.host=redis
spring.data.redis.port=6379

cache.item.ttl=PT1M

catalog.items-per-row=3
catalog.default-page-size=5

spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=market-app
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_MARKET_APP_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://keycloak:8080/realms/my-market

logging.level.org.springframework.r2dbc=INFO