spring.application.name=market-app
server.port=8080

cache.item.ttl=PT1M

catalog.items-per-row=3
catalog.default-page-size=5

spring.session.redis.namespace=my-market:session
spring.session.timeout=30m

logging.level.org.springframework.r2dbc=INFO