services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: my-market-keycloak-dev
    command: start-dev --import-realm
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./docker/keycloak/my-market-realm.json:/opt/keycloak/data/import/my-market-realm.json:ro

  postgres:
    image: postgres:16
    container_name: my-market-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: my-market-app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d my-market-app" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: my-market-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data-dev: