spring.profiles.active=dev

spring.application.name=my-market-app
server.port=8080

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/my-market-app
spring.r2dbc.username=admin
spring.r2dbc.password=admin

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

logging.level.org.springframework.r2dbc=DEBUG