DELETE FROM orders_items;
DELETE FROM cart_items;
DELETE FROM orders;
DELETE FROM items;

ALTER TABLE items ALTER COLUMN id RESTART WITH 1;
ALTER TABLE orders ALTER COLUMN id RESTART WITH 1;
ALTER TABLE orders_items ALTER COLUMN id RESTART WITH 1;
ALTER TABLE cart_items ALTER COLUMN id RESTART WITH 1;